In [32]:
import numpy as np
import pandas as pd
import seaborn as sns

In [33]:
# Import the datasets
train_data = pd.read_csv("Bitext_Sample_Customer_Service_Training_Dataset.csv")
test_data = pd.read_csv("Bitext_Sample_Customer_Service_Testing_Dataset.csv")
validate_data =  pd.read_csv("Bitext_Sample_Customer_Service_validation_Dataset.csv")

Here, we are not worried about the category and tags features, so we can drop them directly.

In [34]:
train_data.drop(["category","tags"],axis=1, inplace=True)

In [35]:
test_data.drop(["category","tags"],axis=1, inplace=True)

In [36]:
validate_data.drop(["category","tags"],axis=1, inplace=True)

Now we have the 2 features that are useful for our further training steps.

Let us see the train data

In [37]:
train_data

utterance        intent
0      would it be possible to cancel the order I made?  cancel_order
1                                      cancelling order  cancel_order
2     I need assistance canceling the last order I h...  cancel_order
3               problem with canceling the order I made  cancel_order
4           I don't know how to cancel the order I made  cancel_order
...                                                 ...           ...
6534  I do not know what I have to do to track the r...  track_refund
6535                                check refund status  track_refund
6536                    help me check the refund status  track_refund
6537  how can I check if there is any updates on my ...  track_refund
6538  how do I check if there is anything wrong with...  track_refund

[6539 rows x 2 columns]

In [38]:
test_data

utterance        intent
0         I have a question about cancelling an order  cancel_order
1                help canceling the order I have made  cancel_order
2    I do not know how to cancel an order I have made  cancel_order
3           where can I cancel the last order I made?  cancel_order
4                  I don't want the last order I made  cancel_order
..                                                ...           ...
813      I am trying to check the status of my refund  track_refund
814                   help checking the refund status  track_refund
815                will you show me my refund status?  track_refund
816                          help to track the refund  track_refund
817                   I am trying to track the refund  track_refund

[818 rows x 2 columns]

In [39]:
validate_data

utterance        intent
0          I want help to cancel the order I have made  cancel_order
1    where can I get information about order cancel...  cancel_order
2                        help to cancel the last order  cancel_order
3           I need help with canceling an order I made  cancel_order
4      I do not know how I can cancel the order I made  cancel_order
..                                                 ...           ...
813                   I try to check the refund status  track_refund
814       I want assistance to check the refund status  track_refund
815  I want assistance checking the status of the r...  track_refund
816                  how can I check my refund status?  track_refund
817                       where do I track the refund?  track_refund

[818 rows x 2 columns]

In [31]:
from sentence_transformers import SentenceTransformer

def ember_v1_model():
    model = SentenceTransformer('llmrails/ember-v1')
    return model

In [32]:
model = ember_v1_model()


In [33]:
features_df = train_data["utterance"]

train_final_list = []
for each_one in features_df:
    temp = model.encode(each_one)
    train_final_list.append(temp)
np.savez("train_features.npz",train_final_list)

In [34]:
test_final_list = []
features_df = test_data["utterance"]
for each_one in features_df:
    temp = model.encode(each_one)
    test_final_list.append(temp)
np.savez("test_features.npz",test_final_list)

In [35]:
features_df = validate_data["utterance"]
validate_final_list = []
for each_one in features_df:
    temp = model.encode(each_one)
    validate_final_list.append(temp)
np.savez("validate_features.npz",validate_final_list)

In [2]:
import numpy as np

In [20]:
train_data_np =  np.load("train_features.npz")
final_train = []
for each in train_data_np:
    for each_one in train_data_np[each]:
        final_train.append(each_one)

In [24]:
len(final_train)


6539

In [86]:
final_train = np.array(final_train)

In [87]:
final_train

array([[-1.3691249 , -0.6410487 , -0.5025571 , ..., -0.00764036,
         0.10406983,  0.21604803],
       [-1.2976571 , -0.49875304, -0.50327754, ..., -0.07431225,
        -0.00407584, -0.15078425],
       [-0.86577034, -0.41718236, -0.7972672 , ...,  0.0173731 ,
         0.3606208 ,  0.21397698],
       ...,
       [-0.76063746, -0.63435304, -0.57827383, ...,  0.00490011,
         0.29214126, -0.34973904],
       [-1.0726885 , -0.52200526, -1.0181926 , ..., -0.0625227 ,
         0.8111133 , -0.44875106],
       [-1.5697381 , -0.4213627 ,  0.00645778, ...,  0.50359565,
         0.8847217 , -0.5201226 ]], dtype=float32)

In [28]:
final_train[0]

array([-1.3691249 , -0.6410487 , -0.5025571 , ..., -0.00764036,
        0.10406983,  0.21604803], dtype=float32)

In [6]:
test_data_np=  np.load("test_features.npz")
final_test = []
for each in test_data_np:
    for each_one in test_data_np[each]:
        final_test.append(each_one)

[[-1.1663187  -0.33771586 -0.52927387 ...  0.08022645 -0.0076628
  -0.18330927]
 [-1.2741491  -0.52940094 -0.40427208 ...  0.04489823  0.33889484
   0.13226089]
 [-1.3634517  -0.3503787  -0.6910494  ... -0.05542524  0.36930454
   0.40507838]
 ...
 [-0.7286261  -0.95845425 -0.71702945 ... -0.22818372  0.70854145
  -0.33313057]
 [-0.70779973 -0.5171747  -0.611316   ... -0.4135635   0.7869561
   0.07037174]
 [-0.90344554 -0.74527895 -0.91667706 ... -0.594457    0.6770198
   0.05837843]]


In [ ]:
len(final_test)

In [7]:
validate_data_np =  np.load("validate_features.npz")
final_validate = []
for each in validate_data_np:
    for each_one in validate_data_np[each]:
        final_validate.append(each_one)

[[-1.3657961  -0.6243776  -0.7116599  ... -0.2378584   0.07071696
   0.36386478]
 [-1.4766105  -0.3849994  -1.2223792  ...  0.15315934  0.32084906
  -0.55768824]
 [-0.6571302  -0.14576875 -0.6051564  ...  0.36052245  0.15119116
   0.04591488]
 ...
 [-0.8223039  -0.722985   -0.72018695 ... -0.11578719  0.563442
  -0.16502263]
 [-1.1998519  -0.5538418  -0.5727353  ... -0.01441332  0.36992216
  -0.36040765]
 [-1.064647   -0.50514835 -0.70793825 ... -0.6125901   0.9412695
  -0.05493889]]


{'cancel_order': 1,
 'change_order': 2,
 'change_shipping_address': 3,
 'check_cancellation_fee': 4,
 'check_invoice': 5,
 'check_payment_methods': 6,
 'check_refund_policy': 7,
 'complaint': 8,
 'contact_customer_service': 9,
 'contact_human_agent': 10,
 'create_account': 11,
 'delete_account': 12,
 'delivery_options': 13,
 'delivery_period': 14,
 'edit_account': 15,
 'get_invoice': 16,
 'get_refund': 17,
 'newsletter_subscription': 18,
 'payment_issue': 19,
 'place_order': 20,
 'recover_password': 21,
 'registration_problems': 22,
 'review': 23,
 'set_up_shipping_address': 24,
 'switch_account': 25,
 'track_order': 26,
 'track_refund': 27}

In [89]:
def read_data():
    import json
    import pandas as pd

    train_data = pd.read_csv("Bitext_Sample_Customer_Service_Training_Dataset.csv")
    test_data = pd.read_csv("Bitext_Sample_Customer_Service_Testing_Dataset.csv")
    validate_data =  pd.read_csv("Bitext_Sample_Customer_Service_validation_Dataset.csv")

    train_data_labels = train_data[["intent"]]
    test_data_labels = test_data[["intent"]]
    validate_data_labels = validate_data[["intent"]]


    with open("mapping.json","r") as f:
        mapping_data = json.load(f)

    mapping_data
    train_data_labels['intent'] = train_data_labels['intent'].map(mapping_data).fillna(train_data_labels['intent'])
    validate_data_labels["intent"] = validate_data_labels["intent"].map(mapping_data).fillna(validate_data_labels["intent"])
    test_data_labels["intent"] = test_data_labels["intent"].map(mapping_data).fillna(test_data_labels["intent"])

    return np.array(train_data_labels), np.array(test_data_labels), np.array(validate_data_labels)

In [90]:
train_labels, test_labels, validate_labels = read_data()

C:\Users\DELL\AppData\Local\Temp\ipykernel_27728\46245637.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data_labels['intent'] = train_data_labels['intent'].map(mapping_data).fillna(train_data_labels['intent'])
C:\Users\DELL\AppData\Local\Temp\ipykernel_27728\46245637.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  validate_data_labels["intent"] = validate_data_labels["intent"].map(mapping_data).fillna(validate_data_labels["intent"])
C:\Users\DELL\AppData\Local\Temp\ipykernel_27728\46245637

In [92]:
train_labels

array([[ 1],
       [ 1],
       [ 1],
       ...,
       [27],
       [27],
       [27]], dtype=int64)